  admin:
    access_log_path: /dev/null
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 8125
  static_resources:
    clusters:
      name: cluster_0
      connect_timeout: 0.25s
      hosts:
        socket_address:
          address: 127.0.0.1
          port_value: 22000
      transport_socket:
        name: vpp
    listeners:
      name: listener_0
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 22001
      filter_chains:
        transport_socket:
          name: vpp
        filters:
          name: envoy.tcp_proxy
          config:
            stat_prefix: tcp_stats
            cluster: cluster_0
